[package]
name = "hardware-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
opencv = "0.92"
dotenv = "0.15"
chrono = "0.4"

[build-dependencies]
tonic-build = "0.12"
